### ISSUE TITLE
Wishlist: SQL::Abstract::SQLite

### ISSUE THREAD

**Issue by augensalat** [Grinnz/Mojo-SQLite#17]
Documentation suggests to use `SQL::Abstract::Pg` for extended SQL options.
However the depedency chain for building that module, which is part of `Mojo::Pg` is quite heavy.
Can't we have a `SQL::Abstract::SQLite` for and in `Mojo-SQLite`?
If you don't want to write that yourself - would you accept a PR?

**Comment by Grinnz** [comment]
Any SQL::Abstract extension I would write or include would not be SQLite specific since there are basically no SQLite-specific components to the extension (though there are some Pg specific components to the current Pg one). Thus it would not be part of this distribution.

**Comment by augensalat** [comment]
So what do you mean? A CPAN distribution `SQL-Abstract-WithOptions`  which is basically the same as a `SQL::Abstract::SQLite` and the lowest common denominator for most RDBMSes?

**Comment by Grinnz** [comment]
That is my idea yes, but mst would prefer that I wait for the [SQL::Abstract redesign](https://metacpan.org/release/MSTROUT/SQL-Abstract-2.000000-TRIAL1).

**Comment by augensalat** [comment]
Oh, didn't know that.
However I don't see right now how that redesign solves the issues here.

**Comment by shadowcat-mst** [comment]
We're -very- nearly there SQL::Abstract wise, and in fact SQL::Abstract::Pg will effectively become obsolete once it ships.

I'm not sure what issues you have that don't appear to be solved - have a look through SQL::Abstract::Reference and the ExtraClauses plugin for a full feature set.

**Comment by augensalat** [comment]
I didn't look so closely, but I think it does not have a `LIMIT`/`OFFSET` implementation.
But maybe this plugin system makes that simpler than how the current `SQL::Abstract::$extension` classes do it.

**Comment by Grinnz** [comment]
SQL::Abstract::Pg is now available as a separate CPAN distribution, so it is now being used directly in 3.006.
