### ISSUE TITLE
Deprecated Mojo::SQLite::PubSub

### ISSUE THREAD

**Issue by Grinnz** [Grinnz/Mojo-SQLite#8]
Opening this ticket in reference to https://github.com/Grinnz/Mojo-SQLite/commit/30156c8c5e156bb5e56a8fc922797a0483c046d3 where I have deprecated Mojo::SQLite::PubSub and the listen/notify methods in Mojo::SQLite::Database. Since SQLite is serverless it can't support client notifications and thus does not really support pubsub, so having a "pubsub" implementation is misleading, when it is really just polling. Possibly a more generic polling system could be built outside of this distribution and referenced by the docs.

**Comment by kraih** [comment]
This is a very good decision. I hate having to point out that pubsub support should be avoided every time i recommend `Mojo::SQLite` to someone.

**Comment by Grinnz** [comment]
Pubsub support has been removed in Mojo::SQLite 3.000.
